name: Lighthouse CI for Netlify sites

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Install & Build
        run: |
          npm install
          npm run build
      - name: Wait for 200 the Netlify Preview
        uses: jakepartusch/wait-for-netlify-action@v1.2
        id: waitFor200
        with:
          site_name: 'elastic-engelbart-26e6d9'
      - name: run Lighthouse CI
        run: |
          npm install -g @lhci/cli@0.6.x
          lhci autorun --collect.url=${{ steps.waitFor200.outputs.url }} --collect.url=${{ steps.waitFor200.outputs.url/pages/about/ }} --collect.numberOfRuns=5
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
